### ISSUE TITLE
Precipitation

### ISSUE THREAD

**Issue by M-Pixel** [maniolias/openweather-node#1]
Is it possible to get the rain and snow precipitation values through your API wrapper?

http://openweathermap.org/weather-data

**Comment by maniolias** [comment]
Of course, for example this code :

``` javascript
var weather = require("Openweather-Node")

weather.now("Lyon",function(err, aData)
{   
    if(err) console.log(err);
    else
    {
        console.log(aData);
    }
})
```

Provide this :

{ type: '',
 values: 
 { coord: { lon: 4.85, lat: 45.75 },
   sys: 
    { message: 0.1961,
      country: 'FR',
      sunrise: 1405483617,
      sunset: 1405538790 },
      weather: [ [Object] ],
      base: 'cmc stations',
      main: 
       { temp: 296.15,
         pressure: 1021,
         humidity: 56,
         temp_min: 296.15,
         temp_max: 296.15 },
      wind: { speed: 2.1, deg: 350, var_beg: 310, var_end: 30 },
      **rain: { '3h': 0 },**
      clouds: { all: 0 },
      dt: 1405499400,
      id: 2996944,
      name: 'Lyon',
      cod: 200 } }

And the snow property appear if openweather provide it.
